[package]
name = "Mnist_cnn_torch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.13.0"
anyhow = "1.0"